apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    environment: {{ .Values.environment }}
spec:
  replicas: {{ index .Values.config .Values.environment "replicaCount" }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        environment: {{ .Values.environment }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
        - name: DATABASE_URL
          value: postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Release.Name }}-db:5432/{{ .Values.database.name }}
        - name: FLASK_RUN_PORT
          value: "{{ .Values.containerPort }}"
        - name: FLASK_ENV
          value: {{ index .Values.config .Values.environment "flaskEnv" }}
        - name: ENVIRONMENT
          value: {{ .Values.environment }}