   apiVersion: v1
   kind: Service
   metadata:
     name: todo-app
     namespace: todo-app-ns
     labels:
       app: todo-app
   spec:
     type: NodePort
     ports:
       - port: 80
         targetPort: 5091
         nodePort: 30166
     selector:
       app: todo-app