version: '3'
services:
  todo-dev:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://todouser:todopassword@todo-db-dev:5432/tododb
    depends_on:
      - todo-db-dev

  todo-prod:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://todouser:todopassword@todo-db-prod:5432/tododb
    depends_on:
      - todo-db-prod

  todo-db-dev:
    image: postgres:13
    environment:
      - POSTGRES_DB=tododb
      - POSTGRES_USER=todouser
      - POSTGRES_PASSWORD=todopassword

  todo-db-prod:
    image: postgres:13
    environment:
      - POSTGRES_DB=tododb
      - POSTGRES_USER=todouser
      - POSTGRES_PASSWORD=todopassword