

replicaCount: 1

image:
  repository: serpantiners/todo-app
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: todo-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

database:
  name: tododb
  user: todouser
  password: todopassword
  host: todo-app-db
  port: 5432

environment: dev

containerPort: 5467

config:
  dev:
    replicaCount: 1
    environment: development
    ingress:
      host: dev-todo-app.local
    flaskEnv: development
  prod:
    replicaCount: 2
    environment: production
    ingress:
      host: prod-todo-app.local
    flaskEnv: production

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}