replicaCount: 1

image:
  repository: serpantiners/todo-app  # Replace *** with your actual DockerHub username
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  nodePort: null  # This allows Kubernetes to assign a random nodePort

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: todo-app-dev.local  # Changed to make it unique for dev environment
      paths:
        - path: /
          pathType: Prefix

database:
  name: your_database_name
  user: your_database_user
  password: your_database_password
  host: todo-app-db
  port: 5432

namePrefix: dev-  # Add this line to create unique resource names