

replicaCount: 1

image:
  repository: serpantiners/todo-app
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}

database:
  name: tododb
  user: todouser
  password: todopassword
  host: todo-app-db
  port: 5432


environment: dev


config:
  dev:
    replicaCount: 1
    environment: development
    ingress:
      host: dev.todo-app.local
  prod:
    replicaCount: 2
    environment: production
    ingress:
      host: todo-app.local

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}