replicaCount: 1

image:
  repository: serpantiners/todo-app
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: todo-app.local
      paths:
        - path: /
          pathType: Prefix

database:
  name: tododb
  user: todouser
  password: todopassword
  host: todo-app-db
  port: 5432

environment: dev  

config:
  dev:
    replicaCount: 1
    ingress:
      host: dev.todo-app.local
  prod:
    replicaCount: 2
    ingress:
      host: todo-app.local
