replicaCount: 1

image:
  repository: your-dockerhub-username/todo-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: todo-app.local
      paths:
        - path: /
          pathType: Prefix

database:
  host: todo-app-db
  port: 5432
  name: your_database_name
  user: your_database_user
  password: your_database_password
