replicaCount: 1

image:
  repository: serpantiners/todo-app  
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  nodePort: null  

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: todo-app-dev.local 
      paths:
        - path: /
          pathType: Prefix

database:
  name: your_database_name
  user: your_database_user
  password: your_database_password
  host: todo-app-db
  port: 5432

namePrefix: dev-  