name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:${{ github.sha }}

  deploy-dev:
    needs: build
    if: github.ref == 'refs/heads/dev' || github.event_name == 'pull_request'
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Dev Minikube
      run: |
        minikube -p minikube-dev status
        kubectl config use-context minikube-dev
        helm upgrade --install todo-app-dev ./helm/todo-app \
          --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/todo-app \
          --set image.tag=${{ github.sha }} \
          --set environment=dev \
          --namespace todo-app-dev-ns \
          --create-namespace

  deploy-prod:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Prod Minikube
      run: |
        minikube -p minikube-prod status
        kubectl config use-context minikube-prod
        helm upgrade --install todo-app-prod ./helm/todo-app \
          --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/todo-app \
          --set image.tag=${{ github.sha }} \
          --set environment=prod \
          --namespace todo-app-prod-ns \
          --create-namespace