name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:${{ github.sha }}
          ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest

  deploy-dev:
    needs: build
    if: github.ref == 'refs/heads/dev' || github.event_name == 'pull_request'
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Dev Minikube
      run: |
        minikube -p minikube-dev status
        kubectl config use-context minikube-dev
        helm upgrade --install todo-app-dev ./helm/todo-app \
          --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/todo-app \
          --set image.tag=${{ github.sha }} \
          --set environment=dev \
          --namespace todo-app-dev-ns \
          --create-namespace

  deploy-prod:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to Prod Minikube
      run: |
        minikube -p minikube-prod status
        kubectl config use-context minikube-prod
        helm upgrade --install todo-app-prod ./helm/todo-app \
          --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/todo-app \
          --set image.tag=${{ github.sha }} \
          --set environment=prod \
          --namespace todo-app-prod-ns \
          --create-namespace

  verify-deployment:
    needs: [deploy-dev, deploy-prod]
    if: always()
    runs-on: self-hosted
    steps:
    - name: Verify Dev Deployment
      if: needs.deploy-dev.result == 'success'
      run: |
        DEV_IMAGE=$(kubectl get deployment todo-app-dev -n todo-app-dev-ns -o jsonpath='{.spec.template.spec.containers[0].image}')
        EXPECTED_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/todo-app:${{ github.sha }}"
        if [ "$DEV_IMAGE" = "$EXPECTED_IMAGE" ]; then
          echo "Dev deployment verified successfully"
        else
          echo "Dev deployment verification failed"
          exit 1
        fi

    - name: Verify Prod Deployment
      if: needs.deploy-prod.result == 'success'
      run: |
        PROD_IMAGE=$(kubectl get deployment todo-app-prod -n todo-app-prod-ns -o jsonpath='{.spec.template.spec.containers[0].image}')
        EXPECTED_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/todo-app:${{ github.sha }}"
        if [ "$PROD_IMAGE" = "$EXPECTED_IMAGE" ]; then
          echo "Prod deployment verified successfully"
        else
          echo "Prod deployment verification failed"
          exit 1
        fi