name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:${{ github.sha }}

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

        - name: Deploy to Minikube
        run: |
          minikube -p minikube-dev status
          kubectl config use-context minikube-dev
          helm upgrade --install todo-app ./helm/todo-app \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/todo-app \
            --set image.tag=${{ github.sha }} \
            --namespace todo-app-ns \
            --create-namespace
      
