name: CI/CD Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/todo-app

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set environment and tag
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          echo "ENV=prod" >> $GITHUB_ENV
          echo "TAG=${{ github.sha }}" >> $GITHUB_ENV
        elif [[ ${{ github.ref }} == 'refs/heads/dev' || ${{ github.event_name }} == 'pull_request' ]]; then
          echo "ENV=dev" >> $GITHUB_ENV
          echo "TAG=dev-${{ github.sha }}" >> $GITHUB_ENV
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:${{ env.TAG }}

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Deploy to Minikube
      run: |
        minikube -p minikube-${{ env.ENV }} status
        kubectl config use-context minikube-${{ env.ENV }}
        helm upgrade --install todo-app-${{ env.ENV }} ./helm/todo-app \
          --set image.repository=${{ env.DOCKER_IMAGE }} \
          --set image.tag=${{ env.TAG }} \
          --namespace todo-app-${{ env.ENV }}-ns \
          --create-namespace
      shell: bash